![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
import numpy as np

my_array = np.arange(10)
print(my_array)
print(my_array.shape)
print(my_array[9:0:-2])

[0 1 2 3 4 5 6 7 8 9]
(10,)
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [3]:
my_array[8:6:-1]

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [4]:
my_array[2::-1]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [5]:
my_array1 = np.arange(1,21)
print(my_array1)

my_array2 = my_array1.reshape(4,5)
print(my_array2)
my_array2[::-1,::-1]


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [6]:
print(my_array2)
my_array2[:2,:2]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [7]:
print(my_array2)
my_array2[::2,::2]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [8]:
my_array2[:3,::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [9]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
loro = x == "Loro"
x[loro]

array(['Loro', 'Loro'], dtype='<U5')

In [10]:
x[np.where(loro)]

array(['Loro', 'Loro'], dtype='<U5')

In [11]:
np.extract(loro, x)

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [12]:
my_array3 = np.arange(20)
my_array3.reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [13]:
print(my_array2)
my_array2[::-1,::-1]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [14]:
m1 = np.zeros((10,))
print(m1.nbytes)
print(m1)

m1[3] = 1
print(m1)

80
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [15]:
m2 = np.arange(10,50)
print(m2)
print(m2.ndim)

print(m2[::-1])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
1
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [16]:
m3 = np.array([1,2,0,0,4,0])
np.nonzero(m3)

(array([0, 1, 4]),)

In [17]:
np.where(m3 != 0)

(array([0, 1, 4]),)

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [18]:
m4 = np.random.random(100)
print(m4.reshape(10,10))

print(np.min(m4))
print(np.max(m4))

[[0.59843201 0.72922777 0.40535905 0.89712895 0.17015928 0.36959505
  0.29639966 0.3264268  0.49513519 0.49981349]
 [0.67484594 0.70384918 0.2357726  0.40105893 0.17795658 0.193955
  0.55872212 0.09157281 0.03854674 0.37161426]
 [0.51566516 0.45695133 0.39277748 0.00192647 0.05821564 0.65411478
  0.61345568 0.20099962 0.9581472  0.52466891]
 [0.11020134 0.6434144  0.5050808  0.00936112 0.79380861 0.07875773
  0.66806932 0.40551375 0.82583162 0.87291963]
 [0.62740596 0.7476343  0.64079779 0.37211042 0.80096943 0.51259294
  0.18459257 0.34253638 0.90174553 0.7744553 ]
 [0.59360951 0.72011069 0.8898239  0.9344413  0.58756173 0.17921795
  0.0334887  0.41827966 0.79869694 0.97807829]
 [0.36848311 0.53781588 0.01383535 0.28708027 0.90016705 0.22863002
  0.23206443 0.34164117 0.7841027  0.93199618]
 [0.01286819 0.07186076 0.246938   0.18495335 0.23409675 0.26735485
  0.8515376  0.00140219 0.49367268 0.92995511]
 [0.76037708 0.63450902 0.92938486 0.15674938 0.26543237 0.57736097
  0.13414963 0

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [19]:
x = np.random.random(30)
print(x)
m = x.mean()
print(m)

[0.14273865 0.46991627 0.45873892 0.26683817 0.51670944 0.74950265
 0.70220094 0.3578782  0.48052584 0.5851463  0.66657491 0.15598917
 0.41240075 0.96383911 0.88176811 0.30525303 0.26264558 0.45511398
 0.09731105 0.85256546 0.59864344 0.0266696  0.98210044 0.67553374
 0.11462504 0.30536275 0.10820542 0.26853543 0.12492431 0.73691699]
0.457505789679143


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [20]:
x = np.ones((10,10))
x[1:-1:,1:-1:] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [21]:
x = np.zeros((8,8), dtype = int)

x[::2,1::2] = 1
x[1::2,::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [31]:
x = np.tile([(0,1), (1,0)], (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 9
Crea una matriz aleatoria de 5x5 y estandariza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [22]:
x = np.random.randint(1,20, (5,5))
x = (x - np.mean(x)/np.std(x))

print(x)

[[ 9.70383442 15.70383442  3.70383442 15.70383442  7.70383442]
 [ 3.70383442 16.70383442 12.70383442 16.70383442  7.70383442]
 [15.70383442  6.70383442 16.70383442  5.70383442  7.70383442]
 [ 3.70383442 11.70383442  5.70383442 -1.29616558  7.70383442]
 [ 7.70383442 14.70383442 16.70383442 16.70383442  3.70383442]]


## Ejercicio 10
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [ ]:
x = np.arange(11)
print(x)

y = x.copy()

y[(y > 3) & (y < 8)] = -1
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -1 -1 -1 -1  8  9 10]
[ 0  1  2  3 -1 -1 -1 -1  8  9 10]


In [26]:
z = x.copy()
z[(z > 3) & (z < 8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


## Ejercicio 11
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**Consejo apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.